### ISSUE TITLE
Avatar is displayed in the wrong location on the map

### ISSUE THREAD

**Issue by andreasolund** [GeReinhart/app-connecting-dartisans#1]
My avatar is displayed 30-40 km away from the location shown on the map in my profile. Could it be related that my colleague is registered from the same coordinates?

**Comment by GeReinhart** [comment]
At some point the profile map wasn't locked, so you could have scrolled and moved your location without knowing it. Can you check again please ?

**Comment by andreasolund** [comment]
Oh, yeah of course! I must have unchecked the map lock the last time, but I've corrected that now.
